openapi: 3.0.3
info:
  title: Chest X-Ray Abnormality Detection API
  description: Backend API for chest X-ray image processing and disease detection
  version: 1.0.0
  contact:
    name: API Support

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /health:
    get:
      summary: Health check endpoint
      operationId: health_check
      tags:
        - System
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time

  /upload:
    post:
      summary: Upload a chest X-ray image (in-memory processing only)
      operationId: upload_image
      tags:
        - Image Upload
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                  description: Chest X-ray image file (PNG/JPG/JPEG, max 10MB)
      responses:
        '200':
          description: Image uploaded and stored in memory
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
        '400':
          description: Invalid file format or size
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /filter/apply:
    post:
      summary: Apply image processing filters to uploaded image
      operationId: apply_filters
      tags:
        - Image Filters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FilterApplyRequest'
      responses:
        '200':
          description: Filters applied successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FilterApplyResponse'
        '400':
          description: Invalid request (unknown image_id or filter names)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Filter processing failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /filter/list:
    get:
      summary: Get list of available filters
      operationId: list_filters
      tags:
        - Image Filters
      responses:
        '200':
          description: List of available filters
          content:
            application/json:
              schema:
                type: object
                properties:
                  filters:
                    type: array
                    items:
                      $ref: '#/components/schemas/FilterInfo'

  /detect/analyze:
    post:
      summary: Detect diseases in chest X-ray image
      operationId: analyze_image
      tags:
        - Disease Detection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DetectionAnalyzeRequest'
      responses:
        '200':
          description: Detection completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetectionAnalyzeResponse'
        '400':
          description: Invalid image_id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Detection failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /results/{filename}:
    get:
      summary: Download processed or annotated image (DEPRECATED - use base64 in responses)
      deprecated: true
      operationId: get_result_image
      tags:
        - Results
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
          description: Filename of processed/annotated image
      responses:
        '410':
          description: Endpoint deprecated - images returned as base64 in filter/detect responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    UploadResponse:
      type: object
      required:
        - image_id
        - filename
        - size_bytes
        - width
        - height
        - format
      properties:
        image_id:
          type: string
          format: uuid
          description: Unique identifier for the uploaded image
        filename:
          type: string
          example: "chest_xray_001.jpg"
        size_bytes:
          type: integer
          example: 2457600
        width:
          type: integer
          example: 1024
        height:
          type: integer
          example: 1024
        format:
          type: string
          enum: [PNG, JPEG, JPG]
        upload_timestamp:
          type: string
          format: date-time

    FilterApplyRequest:
      type: object
      required:
        - image_id
        - filters
      properties:
        image_id:
          type: string
          format: uuid
          description: ID of uploaded image
        filters:
          type: array
          items:
            type: string
            enum:
              - sobel
              - canny
              - gaussian_blur
              - median_filter
              - histogram_equalization
              - fourier_transform
              - dct
              - otsu_thresholding
          minItems: 1
          example: ["sobel", "gaussian_blur"]

    FilterApplyResponse:
      type: object
      required:
        - request_id
        - results
        - total_time_ms
      properties:
        request_id:
          type: string
          format: uuid
        results:
          type: array
          items:
            $ref: '#/components/schemas/ProcessedImageInfo'
        total_time_ms:
          type: integer
          description: Total processing time for all filters
          example: 3245

    ProcessedImageInfo:
      type: object
      required:
        - filter_name
        - image_base64
        - processing_time_ms
      properties:
        filter_name:
          type: string
          example: "sobel"
        display_name:
          type: string
          example: "Sobel Edge Detection"
        image_base64:
          type: string
          description: Base64-encoded processed image (no file storage)
          example: "iVBORw0KGgoAAAANSUhEUgAA..."
        processing_time_ms:
          type: integer
          example: 234

    FilterInfo:
      type: object
      required:
        - name
        - display_name
        - description
      properties:
        name:
          type: string
          example: "sobel"
        display_name:
          type: string
          example: "Sobel Edge Detection"
        description:
          type: string
          example: "Detects edges using Sobel operators"
        parameters:
          type: object
          additionalProperties: true
          description: Fixed filter parameters

    DetectionAnalyzeRequest:
      type: object
      required:
        - image_id
      properties:
        image_id:
          type: string
          format: uuid
          description: ID of uploaded image to analyze

    DetectionAnalyzeResponse:
      type: object
      required:
        - request_id
        - is_normal
        - detections
        - annotated_image_base64
        - inference_time_ms
      properties:
        request_id:
          type: string
          format: uuid
        is_normal:
          type: boolean
          description: True if no abnormalities detected
        detections:
          type: array
          items:
            $ref: '#/components/schemas/DetectionData'
        annotated_image_base64:
          type: string
          description: Base64-encoded annotated image (no file storage)
          example: "iVBORw0KGgoAAAANSUhEUgAA..."
        inference_time_ms:
          type: integer
          example: 567

    DetectionData:
      type: object
      required:
        - class_name_en
        - class_name_vi
        - confidence
        - confidence_tier
        - bbox
        - health_description
        - health_warning
      properties:
        class_name_en:
          type: string
          example: "Pleural effusion"
        class_name_vi:
          type: string
          example: "Tràn dịch màng phổi"
        confidence:
          type: number
          format: float
          minimum: 0.4
          maximum: 1.0
          example: 0.85
        confidence_tier:
          type: string
          enum: [high, medium]
          description: "high: >70%, medium: 40-70%"
        bbox:
          $ref: '#/components/schemas/BoundingBoxData'
        health_description:
          type: string
          description: Vietnamese health information about the condition
        health_warning:
          type: string
          description: Vietnamese medical consultation warning

    BoundingBoxData:
      type: object
      required:
        - x
        - y
        - width
        - height
      properties:
        x:
          type: integer
          description: Top-left X coordinate in pixels
        y:
          type: integer
          description: Top-left Y coordinate in pixels
        width:
          type: integer
          description: Box width in pixels
        height:
          type: integer
          description: Box height in pixels

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          example: "INVALID_FILE_FORMAT"
        message:
          type: string
          example: "File must be PNG, JPG, or JPEG format"
        details:
          type: object
          additionalProperties: true
          description: Additional error context

tags:
  - name: System
    description: System health and status
  - name: Image Upload
    description: Upload chest X-ray images
  - name: Image Filters
    description: Apply image processing filters
  - name: Disease Detection
    description: Detect diseases using AI model
  - name: Results
    description: Download processed images
